### ISSUE TITLE
Images example & Caching

### ISSUE THREAD

**Issue by jtkeyva** [MasahideMori-SimpleAppli/sakura_blizzard#1]
The example doesn't show how images works. Is it possible to to use Image.network? Would be nice to be able to use cached images

thanks

**Comment by MasahideMori-SimpleAppli** [comment]
Hi @jtkeyva ,

Thank you for opening this issue.
I just updated the example.

This package uses Uint8List image files.
Image.network is not available. You need to pass the bytecode (Uint8List) directly to this package.

So, of course, you can cache image data, or you can download it over the network and use it.
However, that part must be implemented by the user. This package does not support it directly.
The example loads an image from an asset.

Thank you.

**Comment by jtkeyva** [comment]
thank you :)
